### ISSUE TITLE
Coding : การนับคะแนน

### ISSUE THREAD

**Issue by InHiBiToRs** [InHiBiToRs/Scratch_project_27#10]

**Comment by InHiBiToRs** [comment]
อันนี้ยังไม่สมบูรณ์นะ

https://scratch.mit.edu/projects/730773585

**Comment by phuennae** [comment]
ลองดูอันนี้ๆ
https://scratch.mit.edu/projects/715626776/

**Comment by phuennae** [comment]
https://scratch.mit.edu/projects/715626776/editor
ทำแค่นับเพิ้มนะอันนี้

**Comment by phuennae** [comment]
อันนี้เราลองทำดู ยังไม่รู้จะใส่เงื่อนไขยังไงเลยทำแบบนี้มาก่อน
https://scratch.mit.edu/projects/731512155/editor
