### ISSUE TITLE
การคิดเกรด

### ISSUE THREAD

**Issue by InHiBiToRs** [InHiBiToRs/Scratch_project_27#15]

**Comment by phuennae** [comment]
https://scratch.mit.edu/projects/732254748/editor

**Comment by InHiBiToRs** [comment]
แน่มันดูไม่ได้อะ แน่ต้องกดแชร์ก่อนนะ

**Comment by phuennae** [comment]
https://scratch.mit.edu/projects/732254748/

**Comment by phuennae** [comment]
https://scratch.mit.edu/projects/732254748/editor/

**Comment by phuennae** [comment]
https://scratch.mit.edu/projects/732254748/
