### ISSUE TITLE
Sound????

### ISSUE THREAD

**Issue by InHiBiToRs** [InHiBiToRs/Scratch_project_27#17]

**Comment by phuennae** [comment]
https://www.youtube.com/watch?v=nzjtkaLCn60&list=PLBtCJCy4TzZTkjWuiIm7RidconrtD_ylj
https://www.youtube.com/watch?v=phBBtaESoMI
effectลองเลือกเอาใน2linkนี้ เราว่าโอเค

**Comment by phuennae** [comment]
https://drive.google.com/drive/folders/1mWkoXsZ1ofg2x_lSNQROQT6DuRBk3QyG?usp=sharing
Sound in game krubb
