### ISSUE TITLE
Model : อาจารย์

### ISSUE THREAD

**Issue by InHiBiToRs** [InHiBiToRs/Scratch_project_27#2]
อยากให้ design ตัวละคร และรูปแบบการเคลื่อนไหวไปมาซ้ายขวา ของอาจารย์มาใส่ในนี้

**Comment by Chamberlain001** [comment]
![Roger_Run_Right_2](https://user-images.githubusercontent.com/110969050/190219063-351aca9a-0653-4b59-bc00-c59f0f6e94d4.png)
![Roger_Main_Left](https://user-images.githubusercontent.com/110969050/190219072-5eaeb72f-9f64-4d4b-8092-4a709992468f.png)
![Roger_Main_Right](https://user-images.githubusercontent.com/110969050/190219076-5d2c8883-4d95-4bb4-ab34-6f6c113ca001.png)
![Roger_Run_Left_1](https://user-images.githubusercontent.com/110969050/190219078-4b78828d-4c49-4b5b-bfd8-a194f72c4a69.png)
![Roger_Run_Left_2](https://user-images.githubusercontent.com/110969050/190219082-50a3cbf7-53a5-4d79-9e7c-9ecc41adf7eb.png)
![Roger_Run_Right_1](https://user-images.githubusercontent.com/110969050/190219086-8b544b0a-a5d1-436a-a534-b256bbbe3637.png)


https://drive.google.com/drive/folders/1DTTVBfRc6q7dBAjgcEHy2Tb2B-1SyyfE?usp=sharing

**Comment by Chamberlain001** [comment]
https://drive.google.com/drive/folders/1DTTVBfRc6q7dBAjgcEHy2Tb2B-1SyyfE?usp=sharing
