### ISSUE TITLE
Model : นักเรียน

### ISSUE THREAD

**Issue by InHiBiToRs** [InHiBiToRs/Scratch_project_27#3]
อยากให้ design ตัวละคร และรูปแบบการเคลื่อนไหวไปมาบนล่างซ้ายขวา ของนักเรียนมาใส่ในนี้

*หากทำได้อยากให้มี นักเรียนมากกว่า 1 แบบ ตามความเหมาะสมของ designer*

**Comment by Chamberlain001** [comment]
อยากให้เป็น pixel art เนอะ เดะจะพยายามทำให้เด้อ

**Comment by Chamberlain001** [comment]
Student Inspired
![images_8](https://user-images.githubusercontent.com/110969050/190070585-27c54d76-5bae-4071-9dbd-b54cac018ef2.jpg)

**Comment by Chamberlain001** [comment]
![Student_1_move2](https://user-images.githubusercontent.com/110969050/190603630-9e813f92-4cfa-4a5c-ba2e-15dcaf42936a.png)
![Student_2_move1](https://user-images.githubusercontent.com/110969050/190603637-0f8e4057-5bd5-4144-862f-fcbfad42699f.png)
![Student_2_move2](https://user-images.githubusercontent.com/110969050/190603642-1b5595f5-7b58-47ad-a82f-31a3bcc394b8.png)
![Student_3_move1](https://user-images.githubusercontent.com/110969050/190603644-72b7ba73-7022-4344-9606-1b8e2a464fd0.png)
![Student_3_move2](https://user-images.githubusercontent.com/110969050/190603646-121d828e-b371-48a5-93cc-a9eae553e0f2.png)
![Student_1_move1](https://user-images.githubusercontent.com/110969050/190603652-c8b8a1cb-0a63-410a-af43-8e67108e4691.png)

https://drive.google.com/drive/folders/1p5Sa0nsJGyCJg_RjYhXijlwxM3XhRNBQ?usp=sharing
