### ISSUE TITLE
Background

### ISSUE THREAD

**Issue by InHiBiToRs** [InHiBiToRs/Scratch_project_27#4]
ฉากหลังทั้งหมดในนี้

- ฉากหน้าแรกเกม
- ฉากตอนโหลดดิ้ง?
- ฉากตอนเลือก stage
- ฉากตอนเล่น
- ฉากอื่นๆ

**Comment by Chamberlain001** [comment]
Main Menu inspired
![Picture1](https://user-images.githubusercontent.com/110969050/190069669-47b6c258-bd87-4ac1-9864-34030f4a15aa.png)

Loading Screen Inspired
![c6dab2-20161027225309_1](https://user-images.githubusercontent.com/110969050/190069867-c31b95c0-1ca3-4dd7-85a3-e7f83f7a9d03.jpg)
อันนี้อยากให้เป็นแบบ หน้าโหลดละก่มี footage ของเกมไรงี้

Stage selection inspired
![zeeshan-tariq-level-selection-1](https://user-images.githubusercontent.com/110969050/190070057-12aa97b5-cd3d-4b79-91c6-5b8657a217ba.jpg)

Game Play Inspired
![lot-cute-space-invaders-pixel-art-style-deep-space-background-vintage-gamescreen_88653-1367](https://user-images.githubusercontent.com/110969050/190070185-c41acd1b-e238-45ca-8475-74a2af0b8082.jpg)

**Comment by Chamberlain001** [comment]
![Main_Game_BG](https://user-images.githubusercontent.com/110969050/190853234-b39e403e-9b2f-4c9a-9d07-43129735799b.png)
 Game BG
https://drive.google.com/file/d/1enkdOYUNLz5k3rrZQ1_yPqKswJc0sDIN/view?usp=sharing

**Comment by Chamberlain001** [comment]
หน้าสรุปผล
![Game_Sum_BG](https://user-images.githubusercontent.com/110969050/190902856-9ddab417-a362-4fb1-88cd-7ee9598f4cbd.png)

เลือก stage 1-3
![Stage_1-3_seletion](https://user-images.githubusercontent.com/110969050/190902859-6d922a5d-5eb8-435e-aabc-57bd67eab9e9.png)

เลือก stage 4-6
![Stage4-6_selection](https://user-images.githubusercontent.com/110969050/190902860-435df69e-2c90-4fe2-955b-d8ccde3f5dea.png)

mid-term/final stage
![Boss_Game_BG](https://user-images.githubusercontent.com/110969050/190902861-5b8a94f0-ed3f-43b7-bd0c-b888c115ca1e.png)

https://drive.google.com/drive/folders/1gP0mzcZyHbStJw3v2kWhl_L3k5XV4BgI?usp=sharing
