### ISSUE TITLE
Weapon : สิ่งของที่อาจารย์และนักเรียนใช้ขว้างใส่กัน

### ISSUE THREAD

**Issue by InHiBiToRs** [InHiBiToRs/Scratch_project_27#5]
อยากให้สิ่งของ ของนักเรียนมี 2-4 อย่าง ( เอาเท่าที่นึกออกนะ )

**Comment by Chamberlain001** [comment]
เอฟเฟคนศตัวแตก
https://user-images.githubusercontent.com/110969050/189840912-e12ec26b-210d-465b-8afb-dd01a0794e32.mov

**Comment by Chamberlain001** [comment]
![Attack_2](https://user-images.githubusercontent.com/110969050/189841349-bd4a8af0-6e75-4a54-a6b9-b50327ede3ba.PNG)
![Attack_1](https://user-images.githubusercontent.com/110969050/189841353-b4a3deda-2b44-4d78-bb36-e8cea481e144.png)
Attack จารโรเจอร์
2อันนี้ต่อกันเลยนะ

**Comment by Chamberlain001** [comment]
> ![Attack_2](https://user-images.githubusercontent.com/110969050/189841349-bd4a8af0-6e75-4a54-a6b9-b50327ede3ba.PNG) ![Attack_1](https://user-images.githubusercontent.com/110969050/189841353-b4a3deda-2b44-4d78-bb36-e8cea481e144.png) Attack จารโรเจอร์

สองอันนี้ต่อกันนะ

**Comment by Chamberlain001** [comment]
![289584274_563532688658978_5720486251175369590_n](https://user-images.githubusercontent.com/110969050/189845507-bcbbe478-bb83-4fcc-aef4-43a7be14eb5e.jpg)
นศ demo

**Comment by Chamberlain001** [comment]
![289584274_563532688658978_5720486251175369590_n (1)](https://user-images.githubusercontent.com/110969050/189845719-c8c25632-7d33-43c5-a6ba-740564be958f.jpg)
นศ demo

**Comment by Chamberlain001** [comment]
![Roger_Attack](https://user-images.githubusercontent.com/110969050/190400426-eb71c226-e19f-449b-9def-a98b05eebd7e.png)

มีวงเล็บด้วยเด้อ แต่มันเป็นสีขาว ละก่ crop มาที่ละตัวเลยก้ได้

**Comment by Chamberlain001** [comment]
![Student_Attack_Pen](https://user-images.githubusercontent.com/110969050/190405053-ccb29fd7-b87e-42b5-86fd-90a8d2ef6ec9.png)
![Student_Attack_Book](https://user-images.githubusercontent.com/110969050/190405060-7b790402-f7b1-4289-825e-582a03c00a5a.png)
![Student_Attack_Eraser](https://user-images.githubusercontent.com/110969050/190405063-feb55fe2-8c4e-40d7-8d46-cdc7c0d22ed3.png)
![Student_Attack_Paper](https://user-images.githubusercontent.com/110969050/190405067-4373029d-b405-4bc2-92f8-baa57d100a90.png)

ของที่นศใช้ปาใส่จาร ปากกา นส ยางลบ กระดาษขยำ
