### ISSUE TITLE
Coding : สิ่งของที่นักเรียนขว้าง

### ISSUE THREAD

**Issue by InHiBiToRs** [InHiBiToRs/Scratch_project_27#9]
การเคลื่อนของสิ่งของที่นักเรียนขว้าง รวมถึงตอนที่มันไปโดนอาจารย์

**Comment by phuennae** [comment]
https://scratch.mit.edu/projects/732785555/

**Comment by InHiBiToRs** [comment]
อันนี้งานทีเราทำนะ
https://scratch.mit.edu/projects/732402435
